# Generated by Django 5.0.14 on 2025-07-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_course_name_student_course_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
