# Generated by Django 5.0.14 on 2025-07-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Activate', 'Activate'), ('Deactivate', 'Deactivate')], default='Activate', max_length=20),
        ),
    ]
