# Generated by Django 5.0.14 on 2025-07-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_course_table_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='Activate', max_length=20),
        ),
    ]
