# Generated by Django 5.0.14 on 2025-07-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_course_createdat_course_updatedat_student_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='createdat',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='updatedat',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='createdat',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='updatedat',
            new_name='updatedAt',
        ),
    ]
