# Generated by Django 5.0.14 on 2025-07-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_createdat_course_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
