# Generated by Django 5.0.14 on 2025-07-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_course_createdat_alter_course_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Activate', 'Activate')], default='Select Choice', max_length=20),
        ),
    ]
